### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/python_etl#3]
ETL code is meant to handle an enormous diversity of inputs gracefully -- far more than we can manually craft unit tests for, or even reason about. I'd like to think us carefully about what forms of automated Q/A make sense. Here are a few:

1) Smoke tests, run under a unit-test framework or similar. These are meant to catch shallow / gross errors, like a linter.
2) Ops-style monitoring.
3) Acceptance tests which focus on **idempotence at medium scale**. Pick a gigabyte of real data, run the existing code against it, and record the output in a dozen assertions. Rerun on PRs and see if the output has changed.

Thoughts?

**Comment by vitillo** [comment]
Tests should exercise most, if not all, code paths of an ETL job, similarly to what we do for our [Scala jobs](https://github.com/mozilla/telemetry-batch-view/blob/master/src/test/scala/com/mozilla/telemetry/CrossSectionalViewTest.scala).

Yes, it isn't perfect but this approach already provides a great deal of value with a relative little investment of time.
